### ISSUE TITLE
cursor flickering issue 

### ISSUE THREAD

**Issue by tami5** [rcarriga/nvim-notify#63]
When ever a new notification is displayed the cursor flickers for the length of the message.

Reproduce `lua vim.lsp.buf.code_action()` on a buffer that doesn't support lsp.

**Comment by rcarriga** [comment]
Unfortunately I don't get any notification triggering the code action call in a non-lsp buffer. The previous issue was due to a slow SSH connection (AFAIK), is there anything similar about your setup that might cause stuttering on fast re-renders?

If you're willing to debug a little, you could try changing how frequently renders occur by editing this line https://github.com/rcarriga/nvim-notify/blob/master/lua/notify/service/init.lua#L25. Current setting is to render every 30ms

**Comment by tami5** [comment]
Hey @rcarriga , hmmm I tried playing around with the render and I'm pretty sure it's nothing todo with. The cursor flickering is the same. 

Nope first time noticing this behavior.

I have this vim settings if relevant 

```lua

vim.o.updatetime = 100
vim.o.redrawtime = 1500
vim.o.lazyredraw = true
vim.o.timeout = true
vim.o.ttimeout = true
vim.o.timeoutlen = 500
vim.o.ttimeoutlen = 10

```

Also I have these cursor related autocmds

```vim
CursorHold    ▏octo://*        ▏ lua require'octo'.on_cursor_hold()                                         
CursorHold    ▏*               ▏ lua require'octo.reviews'.show_review_threads()                            
CursorHold    ▏<buffer=4>      ▏ :silent! lua vim.lsp.buf.document_highlight()                              
CursorHold    ▏<buffer=5>      ▏ :silent! lua vim.lsp.buf.document_highlight()                              
CursorHold    ▏<buffer=3>      ▏ :silent! lua vim.lsp.buf.document_highlight()                              
CursorHold    ▏<buffer=2>      ▏ :silent! lua vim.lsp.buf.document_highlight()                              
CursorHold    ▏<buffer=8>      ▏ :silent! lua vim.lsp.buf.document_highlight()                              
CursorHold    ▏<buffer=5>      ▏ lua require'nvim-treesitter-refactor.highlight_definitions'.highlight_usages(5)
CursorHold    ▏<buffer=3>      ▏ lua require'nvim-treesitter-refactor.highlight_definitions'.highlight_usages(3)
CursorHold    ▏<buffer=2>      ▏ lua require'nvim-treesitter-refactor.highlight_definitions'.highlight_usages(2)  
CursorHold    ▏<buffer=4>      ▏ lua require'nvim-treesitter-refactor.highlight_definitions'.highlight_usages(4)  
CursorHold    ▏<buffer=8>      ▏ lua require'nvim-treesitter-refactor.highlight_definitions'.highlight_usages(8)  
CursorHold    ▏<buffer=171>    ▏ lua require'nvim-treesitter-refactor.highlight_definitions'.highlight_usages(171)
CursorHold    ▏<buffer=207>    ▏ lua require'nvim-treesitter-refactor.highlight_definitions'.highlight_usages(207)
CursorHold    ▏<buffer=189>    ▏ lua require'nvim-treesitter-refactor.highlight_definitions'.highlight_usages(189)

```

which I disabled but still

**Comment by gegoune** [comment]
Most likely related https://github.com/TimUntersberger/neogit/issues/220 - still getting the same issue.

**Comment by gegoune** [comment]
@tami5 could you please confirm if flickering of cursor occurs when there is only single notification displayed? I have just noticed that it flickers for me only when there is more than one at the time.

**Comment by rcarriga** [comment]
@gegoune Following on with https://github.com/TimUntersberger/neogit/issues/220#issuecomment-1089253011 I  just realised i pointed you to the wrong line, you actually need to also change https://github.com/rcarriga/nvim-notify/blob/master/lua/notify/service/init.lua#L37 as well sorry :facepalm:

**Comment by gegoune** [comment]
Ah, now I see the difference! Set both to 500 and got that:

https://user-images.githubusercontent.com/69750637/161841378-43f49f22-ba52-4f19-94ad-899ef6d866a5.mov


But what might be even more important is the fact that with `minimal` renderer as well and blinking is completely gone.

**Comment by rcarriga** [comment]
Ah OK so the flickering still happens but slowly which suggests it's a specific action causing the flickering, not just general rendering. If it doesn't happen for using the minimal renderer then my best guess would be something in the [default renderer](https://github.com/rcarriga/nvim-notify/blob/master/lua/notify/render/default.lua). Sorry I can't test myself since I can't reproduce but you could try removing some of the api calls to remove different parts of the rendering to try pinpoint what might be causing the issue.

If the difference doesn't happen for the minimal one could you also try using the `slide` stages option as that will disable opacity changes, which **I think** also stop the flickering

**Comment by gegoune** [comment]
Will try to bisect default renderer when I get a chance later today. Quickly tested `stages ="slide"` now and it still flickers (on default renderer).

**Comment by gegoune** [comment]
Did not have a chance to properly look into bisecting default renderer, tried quickly and was just erroring due to my edits. But what I discovered now is that flickering happens in wezterm even with minimal nvim configuration. But does not happen in terminal.app whether I use my full or minimal config. Also does not happen in kitty at all. I am sure when I first reported that issue I experienced it on alacritty. Perhaps that will allow you to replicate it? Can you think of why different terminals could behave differently?

**Comment by rcarriga** [comment]
OK thanks for that I was able to reproduce with wezterm :sweat_smile: Definitely looks to be highly dependent  on hardware and the terminal emulator as alacritty and kitty didn't show any for me.

Anyway I've added a few performance improvements but the main one avoids unnecessary rendering. It looks like it helps a lot with the flickering but doesn't eliminate it entirely. Unfortunately I think it would be impossible to guarantee there will never be any flickering since it depends on terminal/hardware.

**Comment by gegoune** [comment]
This is truly amazing! Works so much better already. I will run some more tests later but after quick look flicker seems to be gone! You rock!

**Comment by smithbm2316** [comment]
I can confirm that this seems to be gone in my version of Wezterm as well! Thank you for your timely updates on this particular issue @rcarriga and for your work in general on this plugin. It's such an amazing addition to my Neovim workflow 😄

**Comment by rcarriga** [comment]
I'm probably going to close this unless someone has objections. This entire plugin abuses rendering NeoVim's rendering so as I said I don't think we'll ever get guaranteed perfect rendering and it seems like the worst of it is solved.

**Comment by gegoune** [comment]
Forgot to report back: would still get flicker on occasion but nothing major in terms of frequency. So good to close as far as I am concern.

Out of interest, what do you mean by saying "abuses vim's rendering"?

**Comment by rcarriga** [comment]
I mean I don't think that NeoVim's rendering is designed to redraw multiple windows and redefining multiple highlights 30 times a second :sweat_smile: Though there are performance improvements being made by the core team (e.g. lua controlled highlights) that will continue to make it more performant

**Comment by utkarshgupta137** [comment]
I'm still facing this issue. Changing the render option doesn't help. The only thing that helps is using `static` stage or lowering fps.
Hardware: MBP 14" (M1 Pro)
Term: Alacritty
NeoVim: v0.9.0-dev-1237+gaccdb0104 + AstroNvim v3.2.2

**Comment by rcarriga** [comment]
This is not something that will ever be 100% fixed, it's dependent on the performance of the terminal/GUI. Kitty seems to be the least problematic terminal.

**Comment by utkarshgupta137** [comment]
> This is not something that will ever be 100% fixed, it's dependent on the performance of the terminal/GUI. Kitty seems to be the least problematic terminal.

I've found alacritty to be faster than most terminals I've tried. I don't wanna switch to kitty (because it has a couple of missing features & the author can be very abusive when they're requested). Are there any vim/plugin settings you'd like me to try which can help with this issue? Or perhaps you know why kitty is more performant than alacritty in this case?

**Comment by rcarriga** [comment]
It's hard to pinpoint what will make the difference. The fps, stages and render are the
only settings you can alter within neovim to make a difference, unless you can
find some optimisations within the plugin that I haven't :smile:

The underlying issue is just that nvim-notify works by constantly updating
window highlights and position. This is not something the API was originally
intended for and so it makes sense that it isn't perfect. As to why Kitty works
better here than Alacritty, I don't know I'm just basing that opinion off of
what I and others have seen.

**Comment by utkarshgupta137** [comment]
> It's hard to pinpoint what will make the difference. The fps, stages and render are the only settings you can alter within neovim to make a difference, unless you can find some optimisations within the plugin that I haven't 😄
> 
> The underlying issue is just that nvim-notify works by constantly updating window highlights and position. This is not something the API was originally intended for and so it makes sense that it isn't perfect. As to why Kitty works better here than Alacritty, I don't know I'm just basing that opinion off of what I and others have seen.

I'm hoping https://github.com/alacritty/alacritty/issues/5843 will reduce the issues.

**Comment by davidgm0** [comment]
I can confirm as well that I had this problem with alactritty, but with kitty I don't. I had it with the default mac terminal as well.

**Comment by dgmora** [comment]
I can confirm as well that I had this problem with alactritty, but with kitty I don't. I had it with the default mac terminal as well.

**Comment by nikbrunner** [comment]
Just reporting in, that I am having the same problem in Warp Terminal. When I use Kitty the flickering is gone.

**Comment by AleCandido** [comment]
Only for the sake of reporting: same problem with iTerm2 on MacOS.

I don't care so much about smooth transitions, so I also set `fps = 1`, but it flickers at 1Hz. `fps = 2` clearly doubles the frequency...
